#!/bin/bash

if [ $# -lt 2 ]; then
	echo "error: arguments not set"
	echo "call $0 {src-dir} {dest-dir}"
	echo
	exit
fi

main() {
	echo "task: import"
	gcp -vr $1/* $2

	cd $2

	echo "task: numerize"
	numerizeImages

	# echo "task: resize"
	# resizeImages ${3:-"1920x1440"}

	echo "task: deflicker"
	deflickerImages
	rm *.jpg *.jpg.xmp

	echo "task: create video"
	createVideo "Deflickered/*.jpg" "raw.avi"
	rm -r Deflickered/
}

numerizeImages() {
	counter=1
	ls -1 */*.jpg | while read filename; do mv $filename $(printf %06d $counter).jpg; ((counter++)); done
	rm -R */
}

# resizeImages {X}x{Y}
resizeImages() {
	parallel --no-notice --progress gm mogrify -quality 100 -resize "$1!" ::: *.jpg
}

deflickerImages() {
	`dirname "$(readlink -f "$0")"`/deflicker -p 2
}

# createVideo {input} {output file}
createVideo() {
	ffmpeg -framerate 24 -pattern_type glob -i "$1" -c:v copy $2
}

main "$@"
