#!/bin/bash

if [ $# -ne 4 ]; then
	echo "error: arguments not set"
	echo "call $0 {X}x{Y} {deflicker window} {deflicker runs} {fps} {crf}"
	echo
	echo "resize:"
	echo "full hd: 1920x1080(16:9), 1920x1440(4:3)"
	echo "hd: 1280x720(16:9), 1280x960(4:3)"
	echo
	echo "deflicker: 120 2"
	echo
	echo "fps: 60"
	echo
	echo "crf:"
    echo "10: kb/s:130383.70"
    echo "14: kb/s:39048.89"
    echo "15: kb/s:28017.09"
    echo "16: kb/s:21019.86"
    echo "18: kb/s:11732.31"
    echo "20: kb/s:6390.09"
    echo "22: kb/s:3803.53"
	exit
fi

timelapse-numerize
timelapse-resize $1
timelapse-deflicker -w $2 -p $3
timelapse-ffmpeg $4 'Deflickered/*.jpg' 'output_raw.avi'
timelapse-compress $5 'output_raw.avi' 'output_high.avi'
