#!/bin/bash

if [ $# -ne 3 ]; then
	echo "error: arguments not set"
	echo "call $0 {crf} {input file} {output file}"
    echo
    echo "crf:"
    echo "10: kb/s:130383.70"
    echo "14: kb/s:39048.89"
    echo "15: kb/s:28017.09"
    echo "16: kb/s:21019.86"
    echo "18: kb/s:11732.31"
    echo "20: kb/s:6390.09"
    echo "22: kb/s:3803.53"
	exit
fi

ffmpeg -i $2 -c:v libx264 -preset slow -crf $1 $3
