#!/bin/bash

if [ $# -ne 2 ]; then
	echo "error: arguments not set"
	echo "call $0 {fps} {path}"
	exit
fi

ffmpeg -framerate $1 -pattern_type glob -i "$2" -c:v copy output_raw.avi
ffmpeg -i output_raw.avi -c:v libx264 -preset slow -crf 15 output.mkv
